service:
  security:
    excludeUris:
      - /actuator
      - /actuator/**
      - /doc.html
      - /v3/**
    mock:
      enable: true
      user-id: 1
      username: name
      access: 6
      roles: RD:ADMIN